apiVersion: v1
kind: ServiceAccount
metadata:
  name: flask-app-sa
  namespace: flask-app
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: flask-app-role
  namespace: flask-app
rules:
- apiGroups: [""]
  resources: ["configmaps", "secrets"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["pods", "pods/log"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: flask-app-rolebinding
  namespace: flask-app
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: flask-app-role
subjects:
- kind: ServiceAccount
  name: flask-app-sa
  namespace: flask-app
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: nginx-proxy-sa
  namespace: flask-app
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: nginx-proxy-role
  namespace: flask-app
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: nginx-proxy-rolebinding
  namespace: flask-app
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: nginx-proxy-role
subjects:
- kind: ServiceAccount
  name: nginx-proxy-sa
  namespace: flask-app
